const { chromium } = require("playwright");

(async () => {
  const results = [];
  const consoleErrors = [];
  const pageErrors = [];
  const targetUrl = process.env.TARGET_URL || "http://127.0.0.1:8088/";
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 });
  page.on("console", (msg) => { if (msg.type() === "error") consoleErrors.push(msg.text()); });
  page.on("pageerror", (err) => pageErrors.push(String(err)));
  await page.goto(targetUrl, { waitUntil: "networkidle" });
  await page.waitForSelector(".kpi-card");
  results.push(["desktop_kpis", await page.locator(".kpi-card").count()]);
  results.push(["desktop_rows", await page.locator("#services-table-body tr").count()]);
  results.push(["demo_badge", await page.getByText("Dados demonstrativos", { exact: true }).count()]);
  const dims = await page.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }));
  results.push(["desktop_overflow", dims.sw - dims.cw]);
  const before = await page.locator(".kpi-value").first().textContent();
  await page.selectOption("#range-select", "30days");
  const after = await page.locator(".kpi-value").first().textContent();
  results.push(["range_changed", [before, after]]);
  await page.fill("#service-search", "demonstrativo 10");
  results.push(["filtered_rows", await page.locator("#services-table-body tr").count()]);
  await page.fill("#service-search", "");
  await page.locator(".row-open").nth(8).click();
  results.push(["drawer_open", await page.locator("#service-drawer").getAttribute("aria-hidden")]);
  results.push(["journey_items", await page.locator("#journey-list .journey-item").count()]);
  await page.keyboard.press("Escape");
  results.push(["drawer_closed", await page.locator("#service-drawer").getAttribute("aria-hidden")]);
  await page.click("#refresh-button");
  await page.waitForTimeout(550);
  results.push(["refresh_label", await page.locator("#refresh-label").textContent()]);
  await page.click('[data-section="reservations"]');
  results.push(["nav_preview", await page.locator("#section-preview").isVisible()]);
  await page.click('[data-section="overview"]');
  await page.screenshot({ path: "/work/artifacts/dashboard-desktop.png", fullPage: true });

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  mobile.on("console", (msg) => { if (msg.type() === "error") consoleErrors.push(`mobile:${msg.text()}`); });
  mobile.on("pageerror", (err) => pageErrors.push(`mobile:${String(err)}`));
  await mobile.goto(targetUrl, { waitUntil: "networkidle" });
  await mobile.waitForSelector(".kpi-card");
  const md = await mobile.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth, table: getComputedStyle(document.querySelector("table")).display, cards: getComputedStyle(document.querySelector("#services-mobile-list")).display }));
  results.push(["mobile_overflow", md.sw - md.cw]);
  results.push(["mobile_table", md.table]);
  results.push(["mobile_cards", md.cards]);
  await mobile.locator(".service-mobile-card").first().click();
  results.push(["mobile_drawer_width", await mobile.locator("#service-drawer").evaluate((element) => element.getBoundingClientRect().width)]);
  await mobile.keyboard.press("Escape");
  await mobile.evaluate(() => document.activeElement.blur());
  await mobile.screenshot({ path: "/work/artifacts/dashboard-mobile.png", fullPage: true });
  await browser.close();

  const actual = Object.fromEntries(results);
  console.log(`results=${JSON.stringify(results)}`);
  console.log(`console_errors=${JSON.stringify(consoleErrors)}`);
  console.log(`page_errors=${JSON.stringify(pageErrors)}`);
  if (consoleErrors.length || pageErrors.length) throw new Error("Browser errors detected");
  if (actual.desktop_kpis !== 8 || actual.desktop_rows !== 12 || actual.desktop_overflow !== 0) throw new Error("Desktop contract failed");
  if (JSON.stringify(actual.range_changed) !== JSON.stringify(["248", "1.084"])) throw new Error("Range change failed");
  if (actual.filtered_rows !== 1 || actual.drawer_open !== "false" || actual.drawer_closed !== "true" || actual.journey_items !== 9 || !actual.nav_preview) throw new Error("Interaction contract failed");
  if (actual.mobile_overflow !== 0 || actual.mobile_table !== "none" || actual.mobile_cards !== "grid" || actual.mobile_drawer_width < 389 || actual.mobile_drawer_width > 390) throw new Error("Mobile contract failed");
  console.log("browser_qualification=PASS");
})().catch((error) => { console.error(error); process.exit(1); });
