PRAGMA foreign_keys = ON;

CREATE TABLE handoff_workflows (
    handoff_id TEXT NOT NULL CHECK (length(handoff_id) >= 1) CHECK (instr(handoff_id, char(0)) = 0),
    incident_key TEXT NOT NULL CHECK (length(incident_key) >= 1) CHECK (instr(incident_key, char(0)) = 0),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    status TEXT NOT NULL CHECK (status IN ('requested', 'active', 'acknowledgement_pending', 'acknowledged', 'manual_review', 'completed', 'cancelled')) CHECK (instr(status, char(0)) = 0),
    lead_key_hash TEXT NOT NULL CHECK (length(lead_key_hash) = 64 AND lead_key_hash = lower(lead_key_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(lead_key_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(lead_key_hash, char(0)) = 0),
    state_json TEXT NOT NULL CHECK (length(state_json) >= 1) CHECK (instr(state_json, char(0)) = 0),
    state_hash TEXT NOT NULL CHECK (length(state_hash) = 64 AND state_hash = lower(state_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(state_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(state_hash, char(0)) = 0),
    created_at TEXT NOT NULL CHECK ((((length(created_at) = 25 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(created_at) = 32 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(created_at, 21, 6) != '000000')) AND CAST(substr(created_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(created_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(created_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(created_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(created_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(created_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(created_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(created_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(created_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(created_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(created_at, char(0)) = 0),
    updated_at TEXT NOT NULL CHECK ((((length(updated_at) = 25 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(updated_at) = 32 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(updated_at, 21, 6) != '000000')) AND CAST(substr(updated_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(updated_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(updated_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(updated_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(updated_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(updated_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(updated_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(updated_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(updated_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(updated_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(updated_at, char(0)) = 0),
    CONSTRAINT pk_handoff_workflows PRIMARY KEY (handoff_id),
    CONSTRAINT uq_handoff_workflows_incident_key UNIQUE (incident_key)
) STRICT;

CREATE TABLE handoff_events (
    event_id TEXT NOT NULL CHECK (length(event_id) >= 1) CHECK (instr(event_id, char(0)) = 0),
    handoff_id TEXT NOT NULL CHECK (length(handoff_id) >= 1) CHECK (instr(handoff_id, char(0)) = 0),
    revision INTEGER NOT NULL CHECK (revision >= 1),
    event_type TEXT NOT NULL CHECK (length(event_type) >= 1) CHECK (instr(event_type, char(0)) = 0),
    event_json TEXT NOT NULL CHECK (length(event_json) >= 1) CHECK (instr(event_json, char(0)) = 0),
    event_hash TEXT NOT NULL CHECK (length(event_hash) = 64 AND event_hash = lower(event_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(event_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(event_hash, char(0)) = 0),
    occurred_at TEXT NOT NULL CHECK ((((length(occurred_at) = 25 AND occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(occurred_at) = 32 AND occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(occurred_at, 21, 6) != '000000')) AND CAST(substr(occurred_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(occurred_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(occurred_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(occurred_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(occurred_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(occurred_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(occurred_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(occurred_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(occurred_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(occurred_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(occurred_at, char(0)) = 0),
    CONSTRAINT pk_handoff_events PRIMARY KEY (event_id),
    CONSTRAINT fk_handoff_events_workflow FOREIGN KEY (handoff_id) REFERENCES handoff_workflows (handoff_id),
    CONSTRAINT uq_handoff_events_workflow_revision UNIQUE (handoff_id, revision)
) STRICT;

CREATE TABLE handoff_outbox (
    message_id TEXT NOT NULL CHECK (length(message_id) >= 1) CHECK (instr(message_id, char(0)) = 0),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) >= 1) CHECK (instr(idempotency_key, char(0)) = 0),
    effect_id TEXT NOT NULL CHECK (length(effect_id) >= 1) CHECK (instr(effect_id, char(0)) = 0),
    handoff_id TEXT NOT NULL CHECK (length(handoff_id) >= 1) CHECK (instr(handoff_id, char(0)) = 0),
    kind TEXT NOT NULL CHECK (kind IN ('customer_acknowledgement', 'internal_email')) CHECK (instr(kind, char(0)) = 0),
    template_id TEXT NOT NULL CHECK (length(template_id) >= 1) CHECK (instr(template_id, char(0)) = 0),
    payload_json TEXT NOT NULL CHECK (length(payload_json) >= 1) CHECK (instr(payload_json, char(0)) = 0),
    payload_hash TEXT NOT NULL CHECK (length(payload_hash) = 64 AND payload_hash = lower(payload_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(payload_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(payload_hash, char(0)) = 0),
    status TEXT NOT NULL CHECK (status IN ('pending', 'leased', 'delivered')) CHECK (instr(status, char(0)) = 0),
    claim_owner TEXT CHECK (length(claim_owner) >= 1) CHECK (instr(claim_owner, char(0)) = 0),
    fencing_token INTEGER NOT NULL CHECK (fencing_token >= 0),
    lease_acquired_at TEXT CHECK ((((length(lease_acquired_at) = 25 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_acquired_at) = 32 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_acquired_at, 21, 6) != '000000')) AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_acquired_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_acquired_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_acquired_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_acquired_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_acquired_at, char(0)) = 0),
    lease_expires_at TEXT CHECK ((((length(lease_expires_at) = 25 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_expires_at) = 32 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_expires_at, 21, 6) != '000000')) AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_expires_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_expires_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_expires_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_expires_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_expires_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_expires_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_expires_at, char(0)) = 0),
    delivery_attempts INTEGER NOT NULL CHECK (delivery_attempts >= 0),
    delivered_at TEXT CHECK ((((length(delivered_at) = 25 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(delivered_at) = 32 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(delivered_at, 21, 6) != '000000')) AND CAST(substr(delivered_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(delivered_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(delivered_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(delivered_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(delivered_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(delivered_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(delivered_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(delivered_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(delivered_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(delivered_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(delivered_at, char(0)) = 0),
    receipt_hash TEXT CHECK (receipt_hash IS NULL OR (length(receipt_hash) = 64 AND receipt_hash = lower(receipt_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(receipt_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0)) CHECK (instr(receipt_hash, char(0)) = 0),
    created_at TEXT NOT NULL CHECK ((((length(created_at) = 25 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(created_at) = 32 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(created_at, 21, 6) != '000000')) AND CAST(substr(created_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(created_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(created_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(created_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(created_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(created_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(created_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(created_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(created_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(created_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(created_at, char(0)) = 0),
    updated_at TEXT NOT NULL CHECK ((((length(updated_at) = 25 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(updated_at) = 32 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(updated_at, 21, 6) != '000000')) AND CAST(substr(updated_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(updated_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(updated_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(updated_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(updated_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(updated_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(updated_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(updated_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(updated_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(updated_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(updated_at, char(0)) = 0),
    CONSTRAINT pk_handoff_outbox PRIMARY KEY (message_id),
    CONSTRAINT fk_handoff_outbox_workflow FOREIGN KEY (handoff_id) REFERENCES handoff_workflows (handoff_id),
    CONSTRAINT uq_handoff_outbox_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_handoff_outbox_effect_id UNIQUE (effect_id),
    CONSTRAINT uq_handoff_outbox_receipt_binding UNIQUE (message_id, receipt_hash, delivered_at),
    CONSTRAINT ck_handoff_outbox_lease_tuple CHECK ((claim_owner IS NULL AND lease_acquired_at IS NULL AND lease_expires_at IS NULL) OR (claim_owner IS NOT NULL AND lease_acquired_at IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT ck_handoff_outbox_active_lease CHECK (claim_owner IS NULL OR (fencing_token >= 1 AND lease_expires_at > lease_acquired_at)),
    CONSTRAINT ck_handoff_outbox_receipt_tuple CHECK ((delivered_at IS NULL AND receipt_hash IS NULL) OR (delivered_at IS NOT NULL AND receipt_hash IS NOT NULL)),
    CONSTRAINT ck_handoff_outbox_fencing_history CHECK (fencing_token >= delivery_attempts),
    CONSTRAINT ck_handoff_outbox_status_matrix CHECK ((status = 'pending' AND claim_owner IS NULL AND delivered_at IS NULL) OR (status = 'leased' AND claim_owner IS NOT NULL AND delivered_at IS NULL) OR (status = 'delivered' AND claim_owner IS NULL AND lease_acquired_at IS NULL AND lease_expires_at IS NULL AND fencing_token >= 1 AND delivery_attempts >= 1 AND delivered_at IS NOT NULL))
) STRICT;

CREATE TABLE handoff_receipts (
    receipt_id TEXT NOT NULL CHECK (length(receipt_id) >= 1) CHECK (instr(receipt_id, char(0)) = 0),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) >= 1) CHECK (instr(idempotency_key, char(0)) = 0),
    message_id TEXT NOT NULL CHECK (length(message_id) >= 1) CHECK (instr(message_id, char(0)) = 0),
    receipt_json TEXT NOT NULL CHECK (length(receipt_json) >= 1) CHECK (instr(receipt_json, char(0)) = 0),
    receipt_hash TEXT NOT NULL CHECK (length(receipt_hash) = 64 AND receipt_hash = lower(receipt_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(receipt_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(receipt_hash, char(0)) = 0),
    delivered_at TEXT NOT NULL CHECK ((((length(delivered_at) = 25 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(delivered_at) = 32 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(delivered_at, 21, 6) != '000000')) AND CAST(substr(delivered_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(delivered_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(delivered_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(delivered_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(delivered_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(delivered_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(delivered_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(delivered_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(delivered_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(delivered_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(delivered_at, char(0)) = 0),
    CONSTRAINT pk_handoff_receipts PRIMARY KEY (receipt_id),
    CONSTRAINT fk_handoff_receipts_message FOREIGN KEY (message_id, receipt_hash, delivered_at) REFERENCES handoff_outbox (message_id, receipt_hash, delivered_at),
    CONSTRAINT uq_handoff_receipts_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_handoff_receipts_message_id UNIQUE (message_id)
) STRICT;

CREATE TABLE payment_workflows (
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    status TEXT NOT NULL CHECK (status IN ('awaiting_method', 'awaiting_financial_confirmation', 'awaiting_evidence', 'evidence_verified', 'settlement_queued', 'settling', 'paid', 'retryable', 'manual_review', 'expired', 'cancelled')) CHECK (instr(status, char(0)) = 0),
    state_json TEXT NOT NULL CHECK (length(state_json) >= 1) CHECK (instr(state_json, char(0)) = 0),
    state_hash TEXT NOT NULL CHECK (length(state_hash) = 64 AND state_hash = lower(state_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(state_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(state_hash, char(0)) = 0),
    created_at TEXT NOT NULL CHECK ((((length(created_at) = 25 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(created_at) = 32 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(created_at, 21, 6) != '000000')) AND CAST(substr(created_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(created_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(created_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(created_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(created_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(created_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(created_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(created_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(created_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(created_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(created_at, char(0)) = 0),
    updated_at TEXT NOT NULL CHECK ((((length(updated_at) = 25 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(updated_at) = 32 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(updated_at, 21, 6) != '000000')) AND CAST(substr(updated_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(updated_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(updated_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(updated_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(updated_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(updated_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(updated_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(updated_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(updated_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(updated_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(updated_at, char(0)) = 0),
    CONSTRAINT pk_payment_workflows PRIMARY KEY (payment_id)
) STRICT;

CREATE TABLE payment_events (
    event_id TEXT NOT NULL CHECK (length(event_id) >= 1) CHECK (instr(event_id, char(0)) = 0),
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    revision INTEGER NOT NULL CHECK (revision >= 1),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    event_type TEXT NOT NULL CHECK (length(event_type) >= 1) CHECK (instr(event_type, char(0)) = 0),
    event_json TEXT NOT NULL CHECK (length(event_json) >= 1) CHECK (instr(event_json, char(0)) = 0),
    event_hash TEXT NOT NULL CHECK (length(event_hash) = 64 AND event_hash = lower(event_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(event_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(event_hash, char(0)) = 0),
    occurred_at TEXT NOT NULL CHECK ((((length(occurred_at) = 25 AND occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(occurred_at) = 32 AND occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(occurred_at, 21, 6) != '000000')) AND CAST(substr(occurred_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(occurred_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(occurred_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(occurred_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(occurred_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(occurred_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(occurred_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(occurred_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(occurred_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(occurred_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(occurred_at, char(0)) = 0),
    CONSTRAINT pk_payment_events PRIMARY KEY (event_id),
    CONSTRAINT fk_payment_events_workflow FOREIGN KEY (payment_id) REFERENCES payment_workflows (payment_id),
    CONSTRAINT uq_payment_events_workflow_revision UNIQUE (payment_id, revision)
) STRICT;

CREATE TABLE payment_evidence_claims (
    claim_key TEXT NOT NULL CHECK (length(claim_key) >= 1) CHECK (instr(claim_key, char(0)) = 0),
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    method TEXT NOT NULL CHECK (method IN ('pix', 'wise', 'stripe')) CHECK (instr(method, char(0)) = 0),
    evidence_json TEXT NOT NULL CHECK (length(evidence_json) >= 1) CHECK (instr(evidence_json, char(0)) = 0),
    evidence_hash TEXT NOT NULL CHECK (length(evidence_hash) = 64 AND evidence_hash = lower(evidence_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(evidence_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(evidence_hash, char(0)) = 0),
    status TEXT NOT NULL CHECK (status IN ('in_progress', 'completed', 'retryable', 'manual_review')) CHECK (instr(status, char(0)) = 0),
    claimed_at TEXT NOT NULL CHECK ((((length(claimed_at) = 25 AND claimed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(claimed_at) = 32 AND claimed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(claimed_at, 21, 6) != '000000')) AND CAST(substr(claimed_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(claimed_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(claimed_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(claimed_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(claimed_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(claimed_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(claimed_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(claimed_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(claimed_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(claimed_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(claimed_at, char(0)) = 0),
    consumed_at TEXT CHECK ((((length(consumed_at) = 25 AND consumed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(consumed_at) = 32 AND consumed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(consumed_at, 21, 6) != '000000')) AND CAST(substr(consumed_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(consumed_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(consumed_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(consumed_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(consumed_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(consumed_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(consumed_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(consumed_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(consumed_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(consumed_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(consumed_at, char(0)) = 0),
    CONSTRAINT pk_payment_evidence_claims PRIMARY KEY (claim_key),
    CONSTRAINT fk_payment_evidence_claims_workflow FOREIGN KEY (payment_id) REFERENCES payment_workflows (payment_id),
    CONSTRAINT uq_payment_evidence_claims_binding UNIQUE (claim_key, payment_id, payment_version, economic_signature),
    CONSTRAINT ck_payment_evidence_claims_status_matrix CHECK (((status = 'in_progress' OR status = 'retryable') AND consumed_at IS NULL) OR ((status = 'completed' OR status = 'manual_review') AND consumed_at IS NOT NULL AND consumed_at >= claimed_at))
) STRICT;

CREATE TABLE payment_commands (
    settlement_command_id TEXT NOT NULL CHECK (length(settlement_command_id) >= 1) CHECK (instr(settlement_command_id, char(0)) = 0),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) >= 1) CHECK (instr(idempotency_key, char(0)) = 0),
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    evidence_claim_key TEXT NOT NULL CHECK (length(evidence_claim_key) >= 1) CHECK (instr(evidence_claim_key, char(0)) = 0),
    operation TEXT NOT NULL CHECK (operation IN ('register_and_confirm')) CHECK (instr(operation, char(0)) = 0),
    command_json TEXT NOT NULL CHECK (length(command_json) >= 1) CHECK (instr(command_json, char(0)) = 0),
    command_hash TEXT NOT NULL CHECK (length(command_hash) = 64 AND command_hash = lower(command_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(command_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(command_hash, char(0)) = 0),
    created_at TEXT NOT NULL CHECK ((((length(created_at) = 25 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(created_at) = 32 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(created_at, 21, 6) != '000000')) AND CAST(substr(created_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(created_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(created_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(created_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(created_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(created_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(created_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(created_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(created_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(created_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(created_at, char(0)) = 0),
    CONSTRAINT pk_payment_commands PRIMARY KEY (settlement_command_id),
    CONSTRAINT fk_payment_commands_workflow FOREIGN KEY (payment_id) REFERENCES payment_workflows (payment_id),
    CONSTRAINT fk_payment_commands_evidence FOREIGN KEY (evidence_claim_key, payment_id, payment_version, economic_signature) REFERENCES payment_evidence_claims (claim_key, payment_id, payment_version, economic_signature),
    CONSTRAINT uq_payment_commands_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_commands_subject UNIQUE (payment_id, payment_version, economic_signature),
    CONSTRAINT uq_payment_commands_binding UNIQUE (settlement_command_id, payment_id, payment_version, economic_signature)
) STRICT;

CREATE TABLE payment_ledger (
    settlement_command_id TEXT NOT NULL CHECK (length(settlement_command_id) >= 1) CHECK (instr(settlement_command_id, char(0)) = 0),
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    status TEXT NOT NULL CHECK (status IN ('queued', 'leased', 'dispatch_fenced', 'outcome_recorded', 'manual_review')) CHECK (instr(status, char(0)) = 0),
    claim_owner TEXT CHECK (length(claim_owner) >= 1) CHECK (instr(claim_owner, char(0)) = 0),
    fencing_token INTEGER NOT NULL CHECK (fencing_token >= 0),
    lease_acquired_at TEXT CHECK ((((length(lease_acquired_at) = 25 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_acquired_at) = 32 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_acquired_at, 21, 6) != '000000')) AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_acquired_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_acquired_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_acquired_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_acquired_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_acquired_at, char(0)) = 0),
    lease_expires_at TEXT CHECK ((((length(lease_expires_at) = 25 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_expires_at) = 32 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_expires_at, 21, 6) != '000000')) AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_expires_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_expires_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_expires_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_expires_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_expires_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_expires_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_expires_at, char(0)) = 0),
    claim_count INTEGER NOT NULL CHECK (claim_count >= 0),
    dispatch_slots_consumed INTEGER NOT NULL CHECK (dispatch_slots_consumed >= 0 AND dispatch_slots_consumed <= 1),
    dispatch_request_hash TEXT CHECK (dispatch_request_hash IS NULL OR (length(dispatch_request_hash) = 64 AND dispatch_request_hash = lower(dispatch_request_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(dispatch_request_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0)) CHECK (instr(dispatch_request_hash, char(0)) = 0),
    dispatch_fenced_at TEXT CHECK ((((length(dispatch_fenced_at) = 25 AND dispatch_fenced_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(dispatch_fenced_at) = 32 AND dispatch_fenced_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(dispatch_fenced_at, 21, 6) != '000000')) AND CAST(substr(dispatch_fenced_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(dispatch_fenced_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(dispatch_fenced_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(dispatch_fenced_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(dispatch_fenced_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(dispatch_fenced_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(dispatch_fenced_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(dispatch_fenced_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(dispatch_fenced_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(dispatch_fenced_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(dispatch_fenced_at, char(0)) = 0),
    outcome_certainty TEXT CHECK (outcome_certainty IS NULL OR outcome_certainty IN ('not_dispatched', 'dispatched_no_effect', 'settled', 'partial_settlement', 'dispatched_unknown')) CHECK (instr(outcome_certainty, char(0)) = 0),
    outcome_json TEXT CHECK (length(outcome_json) >= 1) CHECK (instr(outcome_json, char(0)) = 0),
    outcome_hash TEXT CHECK (outcome_hash IS NULL OR (length(outcome_hash) = 64 AND outcome_hash = lower(outcome_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(outcome_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0)) CHECK (instr(outcome_hash, char(0)) = 0),
    outcome_recorded_at TEXT CHECK ((((length(outcome_recorded_at) = 25 AND outcome_recorded_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(outcome_recorded_at) = 32 AND outcome_recorded_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(outcome_recorded_at, 21, 6) != '000000')) AND CAST(substr(outcome_recorded_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(outcome_recorded_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(outcome_recorded_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(outcome_recorded_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(outcome_recorded_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(outcome_recorded_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(outcome_recorded_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(outcome_recorded_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(outcome_recorded_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(outcome_recorded_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(outcome_recorded_at, char(0)) = 0),
    updated_at TEXT NOT NULL CHECK ((((length(updated_at) = 25 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(updated_at) = 32 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(updated_at, 21, 6) != '000000')) AND CAST(substr(updated_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(updated_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(updated_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(updated_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(updated_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(updated_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(updated_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(updated_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(updated_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(updated_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(updated_at, char(0)) = 0),
    CONSTRAINT pk_payment_ledger PRIMARY KEY (settlement_command_id),
    CONSTRAINT fk_payment_ledger_command FOREIGN KEY (settlement_command_id, payment_id, payment_version, economic_signature) REFERENCES payment_commands (settlement_command_id, payment_id, payment_version, economic_signature),
    CONSTRAINT uq_payment_ledger_subject UNIQUE (payment_id, payment_version, economic_signature),
    CONSTRAINT ck_payment_ledger_fencing_history CHECK (fencing_token = claim_count),
    CONSTRAINT ck_payment_ledger_lease_tuple CHECK ((claim_owner IS NULL AND lease_acquired_at IS NULL AND lease_expires_at IS NULL) OR (claim_owner IS NOT NULL AND lease_acquired_at IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT ck_payment_ledger_active_lease CHECK (claim_owner IS NULL OR (fencing_token >= 1 AND lease_expires_at > lease_acquired_at)),
    CONSTRAINT ck_payment_ledger_dispatch_tuple CHECK ((dispatch_slots_consumed = 0 AND dispatch_request_hash IS NULL AND dispatch_fenced_at IS NULL) OR (dispatch_slots_consumed = 1 AND dispatch_request_hash IS NOT NULL AND dispatch_fenced_at IS NOT NULL AND fencing_token >= 1)),
    CONSTRAINT ck_payment_ledger_outcome_tuple CHECK ((outcome_certainty IS NULL AND outcome_json IS NULL AND outcome_hash IS NULL AND outcome_recorded_at IS NULL) OR (outcome_certainty IS NOT NULL AND outcome_json IS NOT NULL AND outcome_hash IS NOT NULL AND outcome_recorded_at IS NOT NULL)),
    CONSTRAINT ck_payment_ledger_status_matrix CHECK ((status = 'queued' AND claim_owner IS NULL AND claim_count >= 0 AND dispatch_slots_consumed = 0 AND outcome_json IS NULL) OR (status = 'leased' AND claim_owner IS NOT NULL AND claim_count >= 1 AND dispatch_slots_consumed = 0 AND outcome_json IS NULL) OR (status = 'dispatch_fenced' AND claim_owner IS NOT NULL AND claim_count >= 1 AND dispatch_slots_consumed = 1 AND outcome_json IS NULL) OR (status = 'outcome_recorded' AND claim_owner IS NULL AND outcome_json IS NOT NULL AND ((outcome_certainty = 'not_dispatched' AND dispatch_slots_consumed = 0) OR (outcome_certainty = 'settled' AND dispatch_slots_consumed = 1))) OR (status = 'manual_review' AND claim_owner IS NULL AND outcome_json IS NOT NULL AND dispatch_slots_consumed = 1 AND outcome_certainty IN ('dispatched_no_effect', 'partial_settlement', 'dispatched_unknown')))
) STRICT;

CREATE TABLE payment_outbox (
    message_id TEXT NOT NULL CHECK (length(message_id) >= 1) CHECK (instr(message_id, char(0)) = 0),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) >= 1) CHECK (instr(idempotency_key, char(0)) = 0),
    effect_id TEXT NOT NULL CHECK (length(effect_id) >= 1) CHECK (instr(effect_id, char(0)) = 0),
    payment_id TEXT NOT NULL CHECK (length(payment_id) >= 1) CHECK (instr(payment_id, char(0)) = 0),
    payment_version INTEGER NOT NULL CHECK (payment_version >= 1),
    economic_signature TEXT NOT NULL CHECK (length(economic_signature) = 64 AND economic_signature = lower(economic_signature) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(economic_signature, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(economic_signature, char(0)) = 0),
    settlement_command_id TEXT NOT NULL CHECK (length(settlement_command_id) >= 1) CHECK (instr(settlement_command_id, char(0)) = 0),
    kind TEXT NOT NULL CHECK (kind IN ('customer_payment_confirmation', 'internal_payment_email', 'booking_form')) CHECK (instr(kind, char(0)) = 0),
    template_id TEXT NOT NULL CHECK (length(template_id) >= 1) CHECK (instr(template_id, char(0)) = 0),
    payload_json TEXT NOT NULL CHECK (length(payload_json) >= 1) CHECK (instr(payload_json, char(0)) = 0),
    payload_hash TEXT NOT NULL CHECK (length(payload_hash) = 64 AND payload_hash = lower(payload_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(payload_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(payload_hash, char(0)) = 0),
    status TEXT NOT NULL CHECK (status IN ('pending', 'leased', 'delivered')) CHECK (instr(status, char(0)) = 0),
    claim_owner TEXT CHECK (length(claim_owner) >= 1) CHECK (instr(claim_owner, char(0)) = 0),
    fencing_token INTEGER NOT NULL CHECK (fencing_token >= 0),
    lease_acquired_at TEXT CHECK ((((length(lease_acquired_at) = 25 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_acquired_at) = 32 AND lease_acquired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_acquired_at, 21, 6) != '000000')) AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_acquired_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_acquired_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_acquired_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_acquired_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_acquired_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_acquired_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_acquired_at, char(0)) = 0),
    lease_expires_at TEXT CHECK ((((length(lease_expires_at) = 25 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(lease_expires_at) = 32 AND lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(lease_expires_at, 21, 6) != '000000')) AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(lease_expires_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(lease_expires_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(lease_expires_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(lease_expires_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(lease_expires_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(lease_expires_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(lease_expires_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(lease_expires_at, char(0)) = 0),
    delivery_attempts INTEGER NOT NULL CHECK (delivery_attempts >= 0),
    delivered_at TEXT CHECK ((((length(delivered_at) = 25 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(delivered_at) = 32 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(delivered_at, 21, 6) != '000000')) AND CAST(substr(delivered_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(delivered_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(delivered_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(delivered_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(delivered_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(delivered_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(delivered_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(delivered_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(delivered_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(delivered_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(delivered_at, char(0)) = 0),
    receipt_hash TEXT CHECK (receipt_hash IS NULL OR (length(receipt_hash) = 64 AND receipt_hash = lower(receipt_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(receipt_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0)) CHECK (instr(receipt_hash, char(0)) = 0),
    created_at TEXT NOT NULL CHECK ((((length(created_at) = 25 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(created_at) = 32 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(created_at, 21, 6) != '000000')) AND CAST(substr(created_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(created_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(created_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(created_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(created_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(created_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(created_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(created_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(created_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(created_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(created_at, char(0)) = 0),
    updated_at TEXT NOT NULL CHECK ((((length(updated_at) = 25 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(updated_at) = 32 AND updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(updated_at, 21, 6) != '000000')) AND CAST(substr(updated_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(updated_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(updated_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(updated_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(updated_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(updated_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(updated_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(updated_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(updated_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(updated_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(updated_at, char(0)) = 0),
    CONSTRAINT pk_payment_outbox PRIMARY KEY (message_id),
    CONSTRAINT fk_payment_outbox_workflow FOREIGN KEY (payment_id) REFERENCES payment_workflows (payment_id),
    CONSTRAINT fk_payment_outbox_command FOREIGN KEY (settlement_command_id, payment_id, payment_version, economic_signature) REFERENCES payment_commands (settlement_command_id, payment_id, payment_version, economic_signature),
    CONSTRAINT uq_payment_outbox_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_outbox_effect_id UNIQUE (effect_id),
    CONSTRAINT uq_payment_outbox_receipt_binding UNIQUE (message_id, receipt_hash, delivered_at),
    CONSTRAINT ck_payment_outbox_lease_tuple CHECK ((claim_owner IS NULL AND lease_acquired_at IS NULL AND lease_expires_at IS NULL) OR (claim_owner IS NOT NULL AND lease_acquired_at IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CONSTRAINT ck_payment_outbox_active_lease CHECK (claim_owner IS NULL OR (fencing_token >= 1 AND lease_expires_at > lease_acquired_at)),
    CONSTRAINT ck_payment_outbox_receipt_tuple CHECK ((delivered_at IS NULL AND receipt_hash IS NULL) OR (delivered_at IS NOT NULL AND receipt_hash IS NOT NULL)),
    CONSTRAINT ck_payment_outbox_fencing_history CHECK (fencing_token >= delivery_attempts),
    CONSTRAINT ck_payment_outbox_status_matrix CHECK ((status = 'pending' AND claim_owner IS NULL AND delivered_at IS NULL) OR (status = 'leased' AND claim_owner IS NOT NULL AND delivered_at IS NULL) OR (status = 'delivered' AND claim_owner IS NULL AND lease_acquired_at IS NULL AND lease_expires_at IS NULL AND fencing_token >= 1 AND delivery_attempts >= 1 AND delivered_at IS NOT NULL))
) STRICT;

CREATE TABLE payment_receipts (
    receipt_id TEXT NOT NULL CHECK (length(receipt_id) >= 1) CHECK (instr(receipt_id, char(0)) = 0),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) >= 1) CHECK (instr(idempotency_key, char(0)) = 0),
    message_id TEXT NOT NULL CHECK (length(message_id) >= 1) CHECK (instr(message_id, char(0)) = 0),
    receipt_json TEXT NOT NULL CHECK (length(receipt_json) >= 1) CHECK (instr(receipt_json, char(0)) = 0),
    receipt_hash TEXT NOT NULL CHECK (length(receipt_hash) = 64 AND receipt_hash = lower(receipt_hash) AND length(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(receipt_hash, '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')) = 0) CHECK (instr(receipt_hash, char(0)) = 0),
    delivered_at TEXT NOT NULL CHECK ((((length(delivered_at) = 25 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+00:00') OR (length(delivered_at) = 32 AND delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]+00:00' AND substr(delivered_at, 21, 6) != '000000')) AND CAST(substr(delivered_at, 1, 4) AS INTEGER) BETWEEN 1 AND 9999 AND CAST(substr(delivered_at, 6, 2) AS INTEGER) BETWEEN 1 AND 12 AND CAST(substr(delivered_at, 9, 2) AS INTEGER) BETWEEN 1 AND (CASE CAST(substr(delivered_at, 6, 2) AS INTEGER) WHEN 2 THEN CASE WHEN ((CAST(substr(delivered_at, 1, 4) AS INTEGER) % 4 = 0 AND CAST(substr(delivered_at, 1, 4) AS INTEGER) % 100 != 0) OR CAST(substr(delivered_at, 1, 4) AS INTEGER) % 400 = 0) THEN 29 ELSE 28 END WHEN 4 THEN 30 WHEN 6 THEN 30 WHEN 9 THEN 30 WHEN 11 THEN 30 ELSE 31 END) AND CAST(substr(delivered_at, 12, 2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr(delivered_at, 15, 2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr(delivered_at, 18, 2) AS INTEGER) BETWEEN 0 AND 59)) CHECK (instr(delivered_at, char(0)) = 0),
    CONSTRAINT pk_payment_receipts PRIMARY KEY (receipt_id),
    CONSTRAINT fk_payment_receipts_message FOREIGN KEY (message_id, receipt_hash, delivered_at) REFERENCES payment_outbox (message_id, receipt_hash, delivered_at),
    CONSTRAINT uq_payment_receipts_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_receipts_message_id UNIQUE (message_id)
) STRICT;
